/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// EDIT THIS FILE!  THIS IS SCAFFOLDING FOR YOU TO OWN!
// NOTE: json tags are required.  Any new fields you add must have json tags for the fields to be serialized.

type Config struct {
	// URL API endpoint of the Kubernetes API server that Vault will communicate with to authenticate service accounts.
	// This is typically the URL of the Kubernetes API server, such as "https://kubernetes.default.svc"
	// when running inside a Kubernetes cluster.
	KubernetesHost string `json:"kubernetes_host,omitempty"`

	// JWT Token used by Vault to authenticate with the Kubernetes API server when
	// validating service account tokens.
	TokenReviewerJwt string `json:"token_reviewer_jwt,omitempty"`

	// TLS kubernetes CA certificate, which can be used to verify the identity of the Kubernetes API server
	// when Vault is configured to communicate with it. This is typically provided as a PEM-encoded certificate.
	// if you get certificate from cluster, use command:
	// kubectl get configmap kube-root-ca.crt -n default -o jsonpath='{.data.ca\.crt}'
	KubernetesCaCert string `json:"kubernetes_ca_cert,omitempty"`
}

type Role struct {
	// ServiceAccountName is the name of the Kubernetes service account that Vault will use
	// to authenticate with the Kubernetes API server.
	BoundServiceAccountName string `json:"bound_service_account_name,omitempty"`

	// ServiceAccountNamespace is the namespace of the Kubernetes service account that Vault will use
	// to authenticate with the Kubernetes API server.
	BoundServiceAccountNamespaces []string `json:"bound_service_account_namespaces,omitempty"`

	// Policies is a list of Vault policies that should be associated with the role. When a token is generated
	// using this role, it will have the permissions defined by these policies. Policies in Vault are used to
	// control access to secrets and other resources, so associating policies with a role allows you to define
	// what actions can be performed by tokens generated for that role.
	Policies []string `json:"policies,omitempty"`

	// Audience is an optional field that can be used to specify the intended audience for tokens generated by this role.
	// This can be used to restrict the use of tokens to specific applications or services that are expected to consume them.
	Audience string `json:"audience,omitempty"`

	// AliasNameSource is an optional field that can be used to specify the source for generating alias names for tokens generated by this role.
	AliasNameSource string `json:"alias_name_source,omitempty"`
}

// AuthMethodSpec defines the desired state of AuthMethod.
type AuthMethodSpec struct {
	// INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
	// Important: Run "make" to regenerate code after modifying this file

	// Type of the auth method in HashiCorp Vault, e.g., "kubernetes", "ldap", "oauth", etc.
	Type string `json:"type,omitempty"`
	// Configuration for the auth method, which may include parameters specific to the type of auth method being configured.
	// This is a free-form string that can be used to pass any necessary configuration details.
	Config Config `json:"config,omitempty"`
	// Role associated with the auth method, which may define specific permissions or policies that
	// should be applied when using this auth method.
	Role Role `json:"role,omitempty"`
}

// AuthMethodStatus defines the observed state of AuthMethod.
type AuthMethodStatus struct {
	// INSERT ADDITIONAL STATUS FIELD - define observed state of cluster
	// Important: Run "make" to regenerate code after modifying this file
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status

// AuthMethod is the Schema for the authmethods API.
type AuthMethod struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   AuthMethodSpec   `json:"spec,omitempty"`
	Status AuthMethodStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AuthMethodList contains a list of AuthMethod.
type AuthMethodList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AuthMethod `json:"items"`
}

func init() {
	SchemeBuilder.Register(&AuthMethod{}, &AuthMethodList{})
}
